# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7d2238c
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
github_repo_name: boilercv
project_description: Computer vision routines suitable for nucleate pool boiling bubble
    analysis.
project_email: blake.naccarato@gmail.com
project_name: boilercv
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2022
