stages:
  binarized_preview:
    cmd: "python -m boilercv.stages.update_previews.binarized"
    deps:
      - "${project_paths.stage_binarized_preview}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}":
          persist: true
  gray_preview:
    cmd: "python -m boilercv.stages.update_previews.gray"
    deps:
      - "${project_paths.stage_gray_preview}"
      - "${paths.sources}"
    outs:
      - "${paths.gray_preview}":
          persist: true

  contours:
    cmd: "python -m boilercv.stages.contours"
    deps:
      - "${project_paths.stage_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true

  fill:
    cmd: "python -m boilercv.stages.fill"
    deps:
      - "${project_paths.stage_fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true
  filled_preview:
    cmd: "python -m boilercv.stages.update_previews.filled"
    deps:
      - "${project_paths.stage_filled_preview}"
      - "${paths.sources}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}":
          persist: true

  unobstructed:
    cmd: "python -m boilercv.stages.unobstructed"
    deps:
      - "${project_paths.stage_unobstructed}"
      - "${paths.contours}"
    outs:
      - "${paths.unobstructed}"

  tracks:
    cmd: "python -m boilercv.stages.tracks"
    deps:
      - "${project_paths.stage_tracks}"
      - "${paths.unobstructed}"
    outs:
      - "${paths.tracks}"

  correlations:
    cmd: "python -m boilercv.stages.correlations"
    deps:
      - "${project_paths.stage_correlations}"
    outs:
      - "${paths.correlations}"

  lifetimes:
    cmd: "python -m boilercv.stages.lifetimes"
    deps:
      - "${project_paths.stage_lifetimes}"
      - "${paths.tracks}"
      - "${paths.correlations}"
    outs:
      - "${paths.lifetimes}"
