stages:
  schema:
    cmd: "python -m boilercv.stages.schema"
    deps:
      - "${paths.stage_schema}"
      - "${paths.paths_module}"
    outs:
      - "${paths.project_schema}"
  check_cv:
    cmd: "python -m boilercv.stages.check_cv"
    deps:
      - "${paths.stage_check_cv}"
      - "${paths.samples}"
  update_binarized_preview:
    cmd: "python -m boilercv.stages.update_binarized_preview"
    deps:
      - "${paths.stage_update_binarized_preview}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}"
  contours:
    cmd: "python -m boilercv.stages.contours"
    deps:
      - "${paths.stage_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true
  fill:
    cmd: "python -m boilercv.stages.fill"
    deps:
      - "${paths.stage_fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true
  update_filled_preview:
    cmd: "python -m boilercv.stages.update_filled_preview"
    deps:
      - "${paths.stage_update_filled_preview}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}"
