project_paths:
  project: .
  requirements: requirements.txt
  dev_requirements: .tools/requirements
  package: src/boilercv
  stages: src/boilercv/stages
  models: src/boilercv/models
  paths_module: src/boilercv/models/paths.py
  plot_config: plotting
  mpl_base: plotting/base.mplstyle
  mpl_hide_title: plotting/hide_title.mplstyle
  stage_build_docs: .tools/scripts/Build-Docs.ps1
  stage_find_contours: src/boilercv/stages/find_contours.py
  stage_fill: src/boilercv/stages/fill.py
  stage_find_tracks: src/boilercv/stages/find_tracks.py
  stage_find_unobstructed: src/boilercv/stages/find_unobstructed.py
  stage_compare_theory: src/boilercv/stages/compare_theory.py
  preview: src/boilercv/stages/preview
  stage_preview_binarized: src/boilercv/stages/preview/preview_binarized.py
  stage_preview_gray: src/boilercv/stages/preview/preview_gray.py
  stage_preview_filled: src/boilercv/stages/preview/preview_filled.py
  correlations: src/boilercv/correlations.py
paths:
  data: data
  contours: data/contours
  docs: data/docs
  docx: data/docx
  examples: data/examples
  filled: data/filled
  lifetimes: data/lifetimes
  rois: data/rois
  samples: data/samples
  sources: data/sources
  tracks: data/tracks
  unobstructed: data/unobstructed
  previews: data/previews
  binarized_preview: data/previews/binarized.nc
  gray_preview: data/previews/gray.nc
  filled_preview: data/previews/filled.nc
