paths:
  file_params: params.yaml
  requirements: requirements.txt
  dev_requirements: .tools/requirements
  package: src/boilercv
  stages: src/boilercv/stages
  models: src/boilercv/models
  paths_module: src/boilercv/models/paths.py
  data: data
  examples: data/examples
  previews: data/previews
  binarized_preview: data/previews/binarized.nc
  contours: data/contours
  rois: data/rois
  samples: data/samples
  sources: data/sources
  project_schema: data/schema
  stage_contours: src/boilercv/stages/contours.py
  stage_schema: src/boilercv/stages/schema.py
  stage_update_binarized_preview: src/boilercv/stages/update_binarized_preview.py
