paths:
  file_params: params.yaml
  requirements: requirements.txt
  dev_requirements: .tools/requirements
  package: src/boilercv
  stages: src/boilercv/stages
  models: src/boilercv/models
  paths_module: src/boilercv/models/paths.py
  data: data
  examples: data/examples
  previews: data/previews
  binarized_preview: data/previews/binarized.nc
  rois: data/rois
  samples: data/samples
  sources: data/sources
  local_data: C:/Users/Blake/.local/boilercv
  cines: C:/Users/Blake/.local/boilercv/cines
  large_examples: C:/Users/Blake/.local/boilercv/large_examples
  large_sources: C:/Users/Blake/.local/boilercv/large_sources
  large_example_cine: C:/Users/Blake/.local/boilercv/cines/2022-01-06T16-57-31.cine
  project_schema: data/schema
  stage_schema: src/boilercv/stages/schema.py
  stage_update_binarized_preview: src/boilercv/stages/update_binarized_preview.py
  local_hierarchical_data: C:/Users/Blake/.local/boilercv/data
