[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv"
requires-python = ">=3.10"
dependencies = [ "matplotlib~=3.6.0", "opencv-contrib-python==4.6.0.66", "scipy~=1.9.1", "dvc[gs]~=2.34.0",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilercv@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilercv"

[project.optional-dependencies]
