[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv"
requires-python = ">=3.11"
dependencies = [ "matplotlib~=3.7.0", "opencv-contrib-python==4.7.0.72", "scipy~=1.10.0", "dvc[gs]~=2.45.1",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilercv@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilercv"

[project.optional-dependencies]
