[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv"
requires-python = ">=3.11"
dependencies = [ "dvc[gs]==2.45.1", "matplotlib==3.7.0", "opencv-contrib-python==4.7.0.72", "pandas==1.5.3", "pandera==0.13.4", "pyarrow==11.0.0", "pydantic==1.10.5", "pyjanitor==0.24.0", "ruamel.yaml==0.17.21", "seaborn==0.12.2", "pyyaml==6.0",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilercv@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilercv"

[project.optional-dependencies]
