name: "dvc"

on: ["workflow_dispatch", "push"]

jobs:
  dvc:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: "projects/326920613558/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@secure-garden-355020.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1.1.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"
